export type Spot = {
  slug: string;
  name: string;
  location: string;
  country: string;
  type: 'surf' | 'ski';
  lat: number;
  lon: number;
  airportCode: string;
  flag: string;
  tagline: string;
  description: string;
  bestMonths: number[];
  flightFrom: string;
  flightPrice: number;
  hotelPrice: number;
  weekendTrip: {
    title: string;
    days: { day: string; plan: string }[];
  };
  weekTrip: {
    title: string;
    days: { day: string; plan: string }[];
  };
  localTips: string[];
  bestBreak?: string;
  bestRun?: string;
  idealConditions?: string;
  idealSwellDirection?: number;
  idealWindDirection?: number;
};

export const ALL_SPOTS: Spot[] = [
  // ── SURF ──────────────────────────────────────────────
  {
    slug: 'pipeline',
    name: 'Pipeline',
    location: 'Oahu, Hawaii',
    country: 'USA',
    type: 'surf',
    lat: 21.6653,
    lon: -158.0530,
    airportCode: 'HNL',
    flag: '🇺🇸',
    tagline: 'The most famous wave on earth',
    description: 'Banzai Pipeline on the North Shore of Oahu is the crown jewel of surfing. A shallow reef break that produces perfect, hollow barrels — when it fires, there is nowhere else on earth you would rather be.',
    bestMonths: [11, 12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 420,
    hotelPrice: 120,
    bestBreak: 'Banzai Pipeline — take off on the peak and aim for the barrel. Backdoor (right) is slightly less crowded.',
    idealConditions: 'NW swell 8-15ft, NE trade winds, low tide',
    weekendTrip: {
      title: 'North Shore Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into HNL, grab a rental car, stay in Haleiwa or Sunset Beach. Hit Foodland Farms for supplies. Sunset surf check at Sunset Beach.' },
        { day: 'Saturday', plan: 'Dawn patrol at Pipeline — get there by 6am before the crowds. Watch from the beach if it is solid overhead+. Afternoon at Waimea Bay. Sunset beers at Haleiwa Joes.' },
        { day: 'Sunday', plan: 'Morning session at Off The Wall or Rockpiles (less crowded than Pipe). Grab a plate lunch at Giovanni\'s Shrimp Truck. Fly home evening.' },
      ]
    },
    weekTrip: {
      title: 'Full North Shore Week',
      days: [
        { day: 'Day 1', plan: 'Arrive, settle in Haleiwa, explore the town, early night.' },
        { day: 'Day 2', plan: 'Dawn patrol Pipeline. Spend the day watching surfers and exploring the beach parks along Kam Highway.' },
        { day: 'Day 3', plan: 'Surf Laniakea or Chuns Reef (more forgiving). Afternoon: drive to the east side, snorkel Hanauma Bay.' },
        { day: 'Day 4', plan: 'Full day North Shore session. Try Sunset Beach if the swell is right. Evening: traditional Hawaiian dinner at Ola at Turtle Bay.' },
        { day: 'Day 5', plan: 'Day trip to Waikiki — surf the long peelers, different vibe, fun waves. See the city side of Oahu.' },
        { day: 'Day 6', plan: 'Hike to the top of Diamond Head in the morning. Afternoon free surf wherever conditions are best.' },
        { day: 'Day 7', plan: 'Final dawn patrol, grab coffee at Haleiwa Coffee Gallery, fly home.' },
      ]
    },
    localTips: [
      'Respect the lineup — Pipeline has a strict local hierarchy. Watch from the beach your first session.',
      'Stay in Haleiwa town — cheaper than Turtle Bay and you are central to everything.',
      'Rent a car — public transport on the North Shore is basically non-existent.',
      'Giovanni\'s Shrimp Truck is not a tourist trap — the garlic shrimp is genuinely incredible.',
      'Check surfline.com/surf-report/banzai-pipeline for the most accurate local forecast.',
      'November to February is peak season — expect crowds in the water and on the road.',
    ],
  },
  {
    slug: 'supertubes',
    name: 'Supertubes',
    location: 'Jeffreys Bay, South Africa',
    country: 'South Africa',
    type: 'surf',
    lat: -34.0522,
    lon: 26.7950,
    airportCode: 'PLZ',
    flag: '🇿🇦',
    tagline: 'The longest, most perfect right-hander on earth',
    description: 'Jeffreys Bay is a small town on the Eastern Cape of South Africa that produces one of the most perfect pointbreaks in the world. Long, fast, mechanical rights that seem to go on forever.',
    bestMonths: [6, 7, 8, 9],
    flightFrom: 'NYC',
    flightPrice: 820,
    hotelPrice: 45,
    bestBreak: 'Supertubes main peak — take off deep and run the wall. Kitchen and Impossibles sections link up on a good day.',
    idealConditions: 'SSW swell 6-10ft, light NW offshore winds, mid tide',
    weekendTrip: {
      title: 'J-Bay Quick Hit',
      days: [
        { day: 'Friday', plan: 'Fly into Port Elizabeth (PLZ), 75min drive to J-Bay. Check into a surf lodge on Da Gama Road — you can see the waves from your room.' },
        { day: 'Saturday', plan: 'All day Supertubes if it is on. The walk from the top of the point back up after each wave is part of the experience. Braai (BBQ) dinner at the lodge.' },
        { day: 'Sunday', plan: 'Morning session, then explore the J-Bay markets and surf shops. Fly back from PLZ in the afternoon.' },
      ]
    },
    weekTrip: {
      title: 'Eastern Cape Surf Week',
      days: [
        { day: 'Day 1', plan: 'Arrive J-Bay, settle in, surf check, early night.' },
        { day: 'Day 2', plan: 'Full day Supertubes — get in the water at dawn before the wind picks up.' },
        { day: 'Day 3', plan: 'If Supers is maxed out, surf Boneyards or Point. Afternoon: visit the Sharks Board display.' },
        { day: 'Day 4', plan: 'Day trip to St Francis Bay — boat-shaped pool at Bruce\'s Beauties, explore the canals.' },
        { day: 'Day 5', plan: 'Back to Supers for another full day. Evening: sundowners at the Walskipper.' },
        { day: 'Day 6', plan: 'Safari day trip to Addo Elephant Park — 1.5hrs from J-Bay, worth every minute.' },
        { day: 'Day 7', plan: 'Final morning session, drive to PLZ, fly home.' },
      ]
    },
    localTips: [
      'J-Bay in July is cold — 4/3mm wetsuit minimum, boots if you run cold.',
      'Da Gama Road is where you want to stay — walking distance to the point.',
      'The rand (ZAR) is weak against USD/EUR — South Africa is incredible value right now.',
      'Watch for sharks — J-Bay has a shark history. Locals surf it anyway but stay aware.',
      'Billabong Pro is held here in July — waves are usually pumping during the contest window.',
      'Hire a local guide for your first session to learn the lineup etiquette.',
    ],
  },
  {
    slug: 'uluwatu',
    name: 'Uluwatu',
    location: 'Bukit Peninsula, Bali',
    country: 'Indonesia',
    type: 'surf',
    lat: -8.8291,
    lon: 115.0849,
    airportCode: 'DPS',
    flag: '🇮🇩',
    tagline: 'Bali\'s most iconic wave at the edge of a clifftop temple',
    description: 'Uluwatu is a world-class left-hander that wraps around the tip of Bali\'s Bukit Peninsula beneath a cliffside Hindu temple. Warm water, consistent swell, and magical sunsets make this one of the most special surf destinations on the planet.',
    bestMonths: [5, 6, 7, 8, 9, 10],
    flightFrom: 'NYC',
    flightPrice: 980,
    hotelPrice: 35,
    bestBreak: 'The Peak for the main takeoff, Racetracks for long walls, The Cave for hollow barrels at low tide.',
    idealConditions: 'SW swell 5-8ft, light SE trade winds, mid to high tide',
    weekendTrip: {
      title: 'Bali Quick Strike',
      days: [
        { day: 'Friday', plan: 'Fly into Ngurah Rai (DPS). Stay at a surf villa in Uluwatu — Omnia area or Bingin. Bintang beers and nasi goreng to recover from the flight.' },
        { day: 'Saturday', plan: 'Dawn session at Uluwatu before the crowds. Afternoon at Padang Padang if the swell is smaller. Sunset at the Uluwatu temple warung.' },
        { day: 'Sunday', plan: 'Morning session at Bingin — more relaxed vibe. Explore the cliff restaurants. Fly home or extend.' },
      ]
    },
    weekTrip: {
      title: 'Bukit Peninsula Week',
      days: [
        { day: 'Day 1', plan: 'Arrive DPS, get to the Bukit, recover, check the breaks.' },
        { day: 'Day 2', plan: 'Full day Uluwatu — morning session, watch from the clifftop warung at noon, afternoon session.' },
        { day: 'Day 3', plan: 'Explore — Padang Padang, Impossibles, Bingin. Find your favourite.' },
        { day: 'Day 4', plan: 'Scooter north to Canggu for a different vibe — beach clubs, Echo Beach surf.' },
        { day: 'Day 5', plan: 'Back on the Bukit. Nyang Nyang beach — 30min walk in, almost always empty.' },
        { day: 'Day 6', plan: 'Sunrise at the Uluwatu temple. Surf Racetracks. Sunset at Single Fin — best view in Bali.' },
        { day: 'Day 7', plan: 'Final morning session, fly home from DPS.' },
      ]
    },
    localTips: [
      'Rent a scooter — it is the only sensible way to get between breaks on the Bukit.',
      'The warung at the top of the Uluwatu stairs has the best view of the lineup. Order a Bintang and watch before paddling out.',
      'Low tide at The Cave produces the most intense barrels — intermediate to advanced only.',
      'Bali is cheap — $35/night gets you a great villa with a pool on the Bukit.',
      'Respect the temple — cover up when visiting Uluwatu temple above the break.',
      'June-August is peak season, still worth it — the trade winds clean it up perfectly.',
    ],
  },
  {
    slug: 'hossegor',
    name: 'Hossegor',
    location: 'Landes, France',
    country: 'France',
    type: 'surf',
    lat: 43.6647,
    lon: -1.4320,
    airportCode: 'BIQ',
    flag: '🇫🇷',
    tagline: 'Europe\'s surf capital — powerful beach break perfection',
    description: 'Hossegor is a small town in southwest France that punches way above its weight in the surf world. A unique underwater canyon funnels Atlantic swell into powerful, hollow beach breaks that rival anything in the world.',
    bestMonths: [9, 10, 11, 3, 4],
    flightFrom: 'NYC',
    flightPrice: 550,
    hotelPrice: 80,
    bestBreak: 'La Gravière for the heaviest barrels, La Nord for more forgiving peaks, Capbreton harbour for beginners.',
    idealConditions: 'NW swell 4-8ft, light E offshore winds, mid tide',
    weekendTrip: {
      title: 'Basque Country Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Biarritz (BIQ), 20min drive to Hossegor. Check into a rental near La Gravière. Dinner in Capbreton — the seafood is outstanding.' },
        { day: 'Saturday', plan: 'Dawn patrol La Gravière if it is pumping. Afternoon explore the markets in Hossegor town. Evening in Biarritz — the grande plage at sunset is stunning.' },
        { day: 'Sunday', plan: 'Morning session, then drive south to San Sebastian (45min) for the best pintxos of your life before flying home.' },
      ]
    },
    weekTrip: {
      title: 'Landes Surf Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Biarritz, drive to Hossegor, settle in.' },
        { day: 'Day 2', plan: 'Full day La Gravière — one of the most powerful beach breaks in Europe.' },
        { day: 'Day 3', plan: 'Surf La Nord in the morning. Afternoon: bike ride through the Landes pine forest.' },
        { day: 'Day 4', plan: 'Day trip to San Sebastian, Spain — 1hr drive, incredible food, great city beach break.' },
        { day: 'Day 5', plan: 'Back to Hossegor. Sunset surf session at Capbreton. Dinner at Le Surfing restaurant.' },
        { day: 'Day 6', plan: 'Explore Biarritz — surf the grande plage, visit the surf museum, explore the old port.' },
        { day: 'Day 7', plan: 'Final session, drive to BIQ, fly home.' },
      ]
    },
    localTips: [
      'La Gravière is not for the faint-hearted — it is a serious beach break that closes out fast. Know your limits.',
      'The Quiksilver Pro France is held here in October — the swell is usually firing during contest season.',
      'Rent a van or camper — it is the classic Hossegor way and cheaper than hotels.',
      'Croissants and coffee at a Hossegor boulangerie before your dawn patrol is non-negotiable.',
      'San Sebastian is 1 hour south and has some of the best food in Europe — go.',
      'Spring (March-April) is underrated — less crowds, still solid swell, mild temperatures.',
    ],
  },
  {
    slug: 'cloudbreak',
    name: 'Cloudbreak',
    location: 'Tavarua Island, Fiji',
    country: 'Fiji',
    type: 'surf',
    lat: -17.8667,
    lon: 177.2167,
    airportCode: 'NAN',
    flag: '🇫🇯',
    tagline: 'The most perfect left in the South Pacific',
    description: 'Cloudbreak is a mythical left-hand reef break off Tavarua Island in Fiji. On its day it produces long, perfect barrels in crystal clear warm water over a shallow coral reef. One of the most coveted waves on earth.',
    bestMonths: [5, 6, 7, 8, 9],
    flightFrom: 'NYC',
    flightPrice: 1100,
    hotelPrice: 150,
    bestBreak: 'The main Cloudbreak peak — take off on the sets and thread the inside sections. Restaurants section offers longer walls.',
    idealConditions: 'SW swell 6-12ft, light SE trade winds, mid tide',
    weekendTrip: {
      title: 'Fiji Quick Strike',
      days: [
        { day: 'Friday', plan: 'Fly into Nadi (NAN). Stay at Waidroka or book a boat trip from the Coral Coast. Long travel day — rest up.' },
        { day: 'Saturday', plan: 'Boat out to Cloudbreak at dawn. Full day session if conditions allow. Sunset kava ceremony with locals.' },
        { day: 'Sunday', plan: 'Morning session, fly home from NAN.' },
      ]
    },
    weekTrip: {
      title: 'Fiji Islands Surf Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Nadi, get to your base on the Coral Coast.' },
        { day: 'Day 2', plan: 'Boat to Cloudbreak — full day, bring lunch.' },
        { day: 'Day 3', plan: 'Boat to Restaurants — longer, more forgiving walls than Cloudbreak.' },
        { day: 'Day 4', plan: 'Rest day — snorkelling the reef, village visit, kava with locals.' },
        { day: 'Day 5', plan: 'Back to Cloudbreak if swell is still up.' },
        { day: 'Day 6', plan: 'Explore the Mamanuca Islands — Monuriki (Cast Away island), snorkel.' },
        { day: 'Day 7', plan: 'Final morning session, fly home.' },
      ]
    },
    localTips: [
      'You need to book a boat — Cloudbreak is only accessible by sea. Arrange in advance.',
      'Booties are essential — the reef is shallow and very sharp on the inside.',
      'Fiji time is real — build extra flexibility into your plans.',
      'Kava is part of the culture — accept it graciously when offered by locals.',
      'June-August produces the most consistent swell but is also the busiest.',
      'The Fijian people are incredibly warm and welcoming — one of the most special travel experiences on earth.',
    ],
  },
  {
    slug: 'puerto-escondido',
    name: 'Puerto Escondido',
    location: 'Oaxaca, Mexico',
    country: 'Mexico',
    type: 'surf',
    lat: 15.8667,
    lon: -97.0667,
    airportCode: 'PXM',
    flag: '🇲🇽',
    tagline: 'The Mexican Pipeline — the heaviest beach break in the world',
    description: 'Puerto Escondido\'s Zicatela beach is home to one of the most powerful and dangerous beach breaks on the planet. Massive closeout sets and perfect barrels on the right days make this a bucket list wave for advanced surfers.',
    bestMonths: [5, 6, 7, 8, 9, 10],
    flightFrom: 'NYC',
    flightPrice: 380,
    hotelPrice: 40,
    bestBreak: 'Zicatela main peak for big barrels, La Punta for long mellow rights, Carrizalillo for beginners.',
    idealConditions: 'S-SW swell 6-12ft, light N offshore winds, low to mid tide',
    weekendTrip: {
      title: 'Puerto Quick Hit',
      days: [
        { day: 'Friday', plan: 'Fly into Puerto Escondido (PXM) or via Mexico City. Stay on Zicatela beach — you can hear the waves from bed.' },
        { day: 'Saturday', plan: 'Dawn patrol Zicatela if it is pumping. Watch from the beach if it is huge — the wipeouts are spectacular. Evening mezcal on the strip.' },
        { day: 'Sunday', plan: 'Morning session at La Punta — longer, more fun waves. Fly home.' },
      ]
    },
    weekTrip: {
      title: 'Oaxacan Coast Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Puerto, get oriented, beach check.' },
        { day: 'Day 2', plan: 'Full day Zicatela — surf or watch depending on size.' },
        { day: 'Day 3', plan: 'Day trip to Mazunte and Zipolite — beautiful beaches, different vibe.' },
        { day: 'Day 4', plan: 'La Punta all day — the right-hander is world class when it links up.' },
        { day: 'Day 5', plan: 'Day trip to Oaxaca city — 6hr bus or short flight. The food alone is worth it.' },
        { day: 'Day 6', plan: 'Back to Zicatela for your best session of the trip.' },
        { day: 'Day 7', plan: 'Final morning, fly home.' },
      ]
    },
    localTips: [
      'Zicatela is NOT a beginner wave — people die here every year. Be honest about your ability.',
      'The town is small and walkable — you do not need a car if you stay on Zicatela.',
      'Mezcal is the local spirit — try it at a proper mezcaleria, not a tourist bar.',
      'June-September is prime season but also peak hurricane season — check forecasts.',
      'La Punta neighbourhood is more chilled than the main Zicatela strip.',
      'Oaxacan food is some of the best in Mexico — mole negro, tlayudas, chapulines.',
    ],
  },
  {
    slug: 'mentawais',
    name: 'Mentawai Islands',
    location: 'West Sumatra, Indonesia',
    country: 'Indonesia',
    type: 'surf',
    lat: -2.1333,
    lon: 99.6833,
    airportCode: 'PDG',
    flag: '🇮🇩',
    tagline: 'The greatest concentration of perfect waves on the planet',
    description: 'The Mentawai Islands off the coast of Sumatra contain more world-class waves per square kilometre than anywhere else on earth. Hollow rights, perfect lefts, warm water, and virtually no crowds if you find the right spot.',
    bestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    flightFrom: 'NYC',
    flightPrice: 1200,
    hotelPrice: 200,
    bestBreak: 'HT\'s for perfect rights, Macaronis for playful lefts, Kandui for hollow barrels.',
    idealConditions: 'SW swell 4-8ft, light E trades, all tides depending on the spot',
    weekendTrip: {
      title: 'Mentawai Boat Charter',
      days: [
        { day: 'Friday', plan: 'Fly into Padang (PDG), board your surf charter boat. Overnight sail to the islands.' },
        { day: 'Saturday', plan: 'Full day surfing — your captain will chase the best conditions. Multiple sessions.' },
        { day: 'Sunday', plan: 'Morning session, sail back to Padang, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Mentawai Week Charter',
      days: [
        { day: 'Day 1', plan: 'Arrive Padang, board the charter boat, sail overnight.' },
        { day: 'Day 2', plan: 'HT\'s or Macaronis depending on swell. 3-4 sessions.' },
        { day: 'Day 3', plan: 'Chase swell — your captain tracks the best waves daily.' },
        { day: 'Day 4', plan: 'Kandui or Rifles if the swell is solid.' },
        { day: 'Day 5', plan: 'Village visit — Mentawai culture is fascinating. Afternoon surf.' },
        { day: 'Day 6', plan: 'Final full day — hit your favourite spot one more time.' },
        { day: 'Day 7', plan: 'Sail back to Padang, fly home.' },
      ]
    },
    localTips: [
      'A surf charter is the best and really the only way to do the Mentawais properly.',
      'Budget $200-400/day for a good charter split between 8-12 people — worth every cent.',
      'Bring a fish — the waves are so good you will want boards for different conditions.',
      'The water is warm (28-30°C) — boardshorts only, no wetsuit needed.',
      'Bring reef boots for the shallower spots — some reefs are very sharp.',
      'The Mentawais are remote — bring all medications, sunscreen, and any specialty items you need.',
    ],
  },
  {
    slug: 'mavericks',
    name: 'Mavericks',
    location: 'Half Moon Bay, California',
    country: 'USA',
    type: 'surf',
    lat: 37.4943,
    lon: -122.5018,
    airportCode: 'SFO',
    flag: '🇺🇸',
    tagline: 'Northern California\'s legendary big wave',
    description: 'Mavericks is one of the most famous big wave spots in the world, breaking off Pillar Point in Half Moon Bay just south of San Francisco. Cold water, giant peaks, and a heavy hold-down make this a spot that commands serious respect.',
    bestMonths: [11, 12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 280,
    hotelPrice: 150,
    bestBreak: 'The main Mavericks peak — outer bowl for the biggest sets, the channel for safety.',
    idealConditions: 'NW swell 15ft+, light NE offshore winds, mid tide',
    weekendTrip: {
      title: 'NorCal Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into SFO. Drive down to Half Moon Bay — 45min. Stay at the Half Moon Bay Inn. Dungeness crab dinner at Barbara\'s Fishtrap.' },
        { day: 'Saturday', plan: 'Dawn patrol at Mavericks — watch from the cliff path if it is massive. Surf the beachbreak at Francis Beach if you want to get in the water. Drive up to San Francisco for the afternoon.' },
        { day: 'Sunday', plan: 'Explore the coast — Pacifica beachbreak, Fort Funston. Fly home from SFO.' },
      ]
    },
    weekTrip: {
      title: 'Northern California Coast Week',
      days: [
        { day: 'Day 1', plan: 'Arrive SFO, drive to Half Moon Bay.' },
        { day: 'Day 2', plan: 'Mavericks watch or surf depending on your level. The view from the cliff is incredible regardless.' },
        { day: 'Day 3', plan: 'Drive north — Ocean Beach SF, a punishing beachbreak for experienced surfers.' },
        { day: 'Day 4', plan: 'Continue north — Bolinas, Stinson Beach. More mellow surf, beautiful scenery.' },
        { day: 'Day 5', plan: 'Day in San Francisco — Golden Gate, Mission burritos, Tartine bakery.' },
        { day: 'Day 6', plan: 'Drive south — Santa Cruz, Steamer Lane. Classic California pointbreak.' },
        { day: 'Day 7', plan: 'Final session, drive back to SFO, fly home.' },
      ]
    },
    localTips: [
      'Mavericks is experts only — it is a life-threatening wave. Watch from the cliff path if in doubt.',
      'The water is cold year round — 5/4mm wetsuit, boots, gloves, and hood in winter.',
      'Half Moon Bay is a beautiful small town — great base for the NorCal coast.',
      'The Mavericks surf contest (when it runs) draws the best big wave surfers in the world.',
      'Parking at the trailhead fills up fast on good swell days — get there early.',
      'Barbara\'s Fishtrap in Princeton-by-the-Sea is the best seafood in the area.',
    ],
  },

  // ── SKI ──────────────────────────────────────────────
  {
    slug: 'whistler',
    name: 'Whistler Blackcomb',
    location: 'British Columbia, Canada',
    country: 'Canada',
    type: 'ski',
    lat: 50.1163,
    lon: -122.9574,
    airportCode: 'YVR',
    flag: '🇨🇦',
    tagline: 'The biggest ski resort in North America',
    description: 'Whistler Blackcomb is a giant — two massive mountains connected by the Peak 2 Peak gondola, over 8,100 acres of skiable terrain, and a legendary village at the base. Two-and-a-half hours north of Vancouver in one of the most beautiful mountain settings on earth.',
    bestMonths: [12, 1, 2, 3, 4],
    flightFrom: 'NYC',
    flightPrice: 280,
    hotelPrice: 180,
    bestRun: 'Spanky\'s Ladder on Blackcomb for big mountain feel, Harmony Bowl on Whistler for powder days.',
    idealConditions: 'Fresh snowfall overnight, cold temperatures, light winds',
    weekendTrip: {
      title: 'Whistler Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Vancouver (YVR). Rent a car or take the Whistler Shuttle (easier). Arrive Whistler village, grab gear from rental shops on Village Stroll. Dinner at Araxi.' },
        { day: 'Saturday', plan: 'On snow by 8:30am — Whistler Mountain first, hit Harmony Bowl, then Peak chair. Lunch at Roundhouse Lodge. Afternoon on Blackcomb. Après ski at Garfinkel\'s.' },
        { day: 'Sunday', plan: 'Early start Blackcomb — Spanky\'s Ladder if conditions allow. Afternoon: speed down easier groomers before driving back to YVR.' },
      ]
    },
    weekTrip: {
      title: 'Whistler Full Week',
      days: [
        { day: 'Day 1', plan: 'Arrive, get settled, afternoon ski to get your legs.' },
        { day: 'Day 2', plan: 'Full day Whistler Mountain — explore every zone.' },
        { day: 'Day 3', plan: 'Full day Blackcomb — Glacier, 7th Heaven, Spanky\'s.' },
        { day: 'Day 4', plan: 'Powder day plan — whichever mountain got the most snow. Hit trees early before they get tracked out.' },
        { day: 'Day 5', plan: 'Snowmobile tour or cat skiing in the backcountry for something different.' },
        { day: 'Day 6', plan: 'Peak 2 Peak day — ski from one mountain to the other all day.' },
        { day: 'Day 7', plan: 'Final morning laps, drive back to Vancouver, fly home.' },
      ]
    },
    localTips: [
      'Buy lift tickets in advance online — they are significantly cheaper and sometimes sell out.',
      'Stay in Whistler Village or Upper Village — ski-in ski-out makes the whole trip easier.',
      'Powder days happen fast — follow @WhistlerBlackcomb on Instagram for overnight snow alerts.',
      'The Peak 2 Peak gondola has glass-bottomed cabins — do this at least once even if you are not skiing.',
      'Après ski culture at Whistler is serious — GLC and Longhorn Saloon are the classics.',
      'February is the sweet spot — good snowpack, fewer holiday crowds than December-January.',
    ],
  },
  {
    slug: 'snowbird',
    name: 'Snowbird',
    location: 'Little Cottonwood Canyon, Utah',
    country: 'USA',
    type: 'ski',
    lat: 40.5830,
    lon: -111.6556,
    airportCode: 'SLC',
    flag: '🇺🇸',
    tagline: 'Greatest snow on earth — Utah\'s crown jewel',
    description: 'Snowbird sits at the top of Little Cottonwood Canyon, 29 miles from Salt Lake City. Utah\'s legendary light, dry powder combined with Snowbird\'s steep terrain and 3,000ft vertical drop make this one of the most exciting ski mountains in the world.',
    bestMonths: [12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 180,
    hotelPrice: 120,
    bestRun: 'Regulator Johnson for steep powder, The Cirque for big mountain terrain, Chips Run for intermediate cruising.',
    idealConditions: 'Storm cycle dropping 12"+ overnight, cold temperatures, groomed morning',
    weekendTrip: {
      title: 'SLC Powder Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Salt Lake City (SLC) — one of the closest airports to world class skiing anywhere. 45min drive up the canyon. Dinner at The Aerie at the Snowbird Center.' },
        { day: 'Saturday', plan: 'On the tram at 9am. Mineral Basin for morning warm up, then Cirque traverse for big mountain terrain. Afternoon groomers when legs start burning.' },
        { day: 'Sunday', plan: 'If it snowed overnight hit the trees first thing. Drive back to SLC for afternoon flight.' },
      ]
    },
    weekTrip: {
      title: 'Wasatch Week',
      days: [
        { day: 'Day 1', plan: 'Arrive SLC, drive up canyon, get settled.' },
        { day: 'Day 2', plan: 'Full day Snowbird — learn the mountain layout.' },
        { day: 'Day 3', plan: 'Day trip to Alta — skiers only, incredible snow, old-school charm. Shares a ridgeline with Snowbird.' },
        { day: 'Day 4', plan: 'Back to Snowbird — Mineral Basin all day if conditions are good.' },
        { day: 'Day 5', plan: 'Park City day trip — 45min drive, different terrain, great town.' },
        { day: 'Day 6', plan: 'Powder day at Snowbird — wake up at 6am, check the snow report, get on the tram first chair.' },
        { day: 'Day 7', plan: 'Final morning, drive to SLC, fly home.' },
      ]
    },
    localTips: [
      'Utah\'s snow is famously light and dry — it skis completely differently to heavy East Coast snow.',
      'The tram holds 125 people and has a long line on weekends — get there early or ski the lifts first.',
      'Alta is next door and has some of the best snow in Utah — combine both mountains in a trip.',
      'SLC airport is genuinely 45 minutes from world class skiing — one of the best ski access points in the world.',
      'Snowbird has terrain for all levels but its reputation is for experts — intermediates will love Mineral Basin.',
      'The canyon road can close after heavy snowfall — check UDOT road conditions before driving up.',
    ],
  },
  {
    slug: 'niseko',
    name: 'Niseko United',
    location: 'Hokkaido, Japan',
    country: 'Japan',
    type: 'ski',
    lat: 42.8042,
    lon: 140.6875,
    airportCode: 'CTS',
    flag: '🇯🇵',
    tagline: 'The powder capital of the world',
    description: 'Niseko on Japan\'s northernmost island of Hokkaido receives some of the most consistent, light, dry powder snow on earth — up to 15 metres per season. Combined with Japanese culture, incredible food, and an onsen on every corner, this is a ski destination unlike any other.',
    bestMonths: [12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 780,
    hotelPrice: 120,
    bestRun: 'Hanazono for untouched powder stashes, Gate 3 backcountry for the adventurous, Ace Family for long cruising runs.',
    idealConditions: 'Siberian storm cycle dropping powder overnight, cold temperatures below -5°C',
    weekendTrip: {
      title: 'Niseko Powder Hit',
      days: [
        { day: 'Friday', plan: 'Fly into New Chitose (CTS). Bus or hire car 2hrs to Niseko. Check into a lodge in Hirafu village. Ramen dinner to warm up.' },
        { day: 'Saturday', plan: 'If it snowed — trees at Hanazono first thing before they get tracked. Midday groomer run warm up. Afternoon backcountry gates if you are experienced. Onsen at the hotel.' },
        { day: 'Sunday', plan: 'Morning session on Annupuri or Grand Hirafu. Drive back to CTS, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Hokkaido Ski Week',
      days: [
        { day: 'Day 1', plan: 'Arrive CTS, bus to Niseko, get settled in Hirafu.' },
        { day: 'Day 2', plan: 'Grand Hirafu — get your powder legs.' },
        { day: 'Day 3', plan: 'Hanazono — smaller mountain, incredible tree runs.' },
        { day: 'Day 4', plan: 'Annupuri — the locals\' mountain, less crowds, great powder.' },
        { day: 'Day 5', plan: 'Backcountry tour with a guide — the terrain outside the gates is world class.' },
        { day: 'Day 6', plan: 'Day trip to Rusutsu — neighbouring resort, massive and often uncrowded.' },
        { day: 'Day 7', plan: 'Final morning laps, bus to CTS, fly home.' },
      ]
    },
    localTips: [
      'Japan\'s powder is the lightest in the world — it skis like floating on air. Completely different to anywhere else.',
      'The backcountry gates at Niseko open when the patrol decides — check in the morning and be ready to go.',
      'An onsen (hot spring bath) after skiing is mandatory — most lodges have one or use the public baths.',
      'Hirafu village has an incredible restaurant scene — the Japanese food is exceptional.',
      'January is statistically the best powder month — book early as it fills up fast.',
      'Rent skis in Hirafu rather than bringing your own — good quality, cheaper, and saves the hassle.',
    ],
  },
  {
    slug: 'chamonix',
    name: 'Chamonix',
    location: 'Haute-Savoie, France',
    country: 'France',
    type: 'ski',
    lat: 45.9237,
    lon: 6.8694,
    airportCode: 'GVA',
    flag: '🇫🇷',
    tagline: 'The birthplace of alpinism — big mountain skiing at its finest',
    description: 'Chamonix sits in the shadow of Mont Blanc, Europe\'s highest peak. It is less a ski resort and more a world-class mountain town that happens to have extraordinary skiing. The Vallée Blanche — a 20km off-piste glacier run — is one of the greatest skiing experiences on earth.',
    bestMonths: [1, 2, 3, 4],
    flightFrom: 'NYC',
    flightPrice: 650,
    hotelPrice: 120,
    bestRun: 'Vallée Blanche for the epic glacier descent, Les Grands Montets for steep off-piste, Brévent for the Mont Blanc views.',
    idealConditions: 'Fresh snow, clear skies for the Vallée Blanche, cold temperatures to keep the powder dry',
    weekendTrip: {
      title: 'Cham Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Geneva (GVA). 1hr transfer to Chamonix. Check into a hotel in town. Fondue and vin chaud in one of the historic chalets.' },
        { day: 'Saturday', plan: 'Aiguille du Midi cable car at 8am — the views of Mont Blanc are staggering. Ski Les Grands Montets. Après ski at MBC (Mont Blanc Brewing Company).' },
        { day: 'Sunday', plan: 'Vallée Blanche if conditions allow — book a guide in advance. Drive back to Geneva, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Mont Blanc Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Geneva, transfer to Chamonix, get settled.' },
        { day: 'Day 2', plan: 'Les Grands Montets — the steepest and most challenging skiing in the valley.' },
        { day: 'Day 3', plan: 'Brévent and Flégère — incredible views across to Mont Blanc.' },
        { day: 'Day 4', plan: 'Vallée Blanche with a guide — the most famous off-piste run in the world.' },
        { day: 'Day 5', plan: 'Day trip to Verbier — 1.5hr drive, completely different vibe, great terrain.' },
        { day: 'Day 6', plan: 'Le Tour and Balme — gentler terrain, beautiful scenery, great for a powder day.' },
        { day: 'Day 7', plan: 'Final morning, transfer to Geneva, fly home.' },
      ]
    },
    localTips: [
      'The Vallée Blanche requires a guide — do not attempt it without one. It is a glacier with crevasses.',
      'Chamonix town is beautiful — spend time in the streets, the food and wine scene is excellent.',
      'The ski areas are spread around the valley — a bus pass is included with your lift ticket.',
      'January-February is best for snow but can have bad weather — March has more stable conditions and spring sun.',
      'Book the Aiguille du Midi cable car in advance — it sells out, especially on clear days.',
      'The MBC (Mont Blanc Brewing Company) is the best après ski spot in town.',
    ],
  },
  {
    slug: 'verbier',
    name: 'Verbier',
    location: 'Valais, Switzerland',
    country: 'Switzerland',
    type: 'ski',
    lat: 46.0959,
    lon: 7.2283,
    airportCode: 'GVA',
    flag: '🇨🇭',
    tagline: 'Switzerland\'s most glamorous ski resort',
    description: 'Verbier is the jewel of the Swiss 4 Vallées ski area — a glamorous, high-altitude resort with world-class off-piste terrain, legendary après ski, and the famous Freeride World Tour stop. Big mountain terrain for confident skiers.',
    bestMonths: [1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 700,
    hotelPrice: 200,
    bestRun: 'Mont Fort off-piste for big mountain feel, Lac des Vaux for powder, Stairway to Heaven couloir for experts.',
    idealConditions: 'Fresh powder, high pressure for clear skies, cold temperatures',
    weekendTrip: {
      title: 'Verbier Weekend',
      days: [
        { day: 'Friday', plan: 'Fly Geneva, transfer to Verbier. Switzerland is expensive — budget accordingly. Dinner at Sonalon or Les Ruinettes.' },
        { day: 'Saturday', plan: 'Mont Fort cable car first thing — the highest point and best views. Off-piste from the top if conditions allow. Après at Farm Club or Fer à Cheval.' },
        { day: 'Sunday', plan: 'Morning laps, transfer back to Geneva, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Swiss Alps Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Geneva, transfer to Verbier.' },
        { day: 'Day 2', plan: 'Explore the 4 Vallées — massive interconnected ski area.' },
        { day: 'Day 3', plan: 'Mont Fort and the off-piste zones with a guide.' },
        { day: 'Day 4', plan: 'Day trip to Zermatt and the Matterhorn — unforgettable.' },
        { day: 'Day 5', plan: 'Powder day — wherever it snowed most.' },
        { day: 'Day 6', plan: 'Day trip to Chamonix across the border in France.' },
        { day: 'Day 7', plan: 'Final morning, transfer to Geneva, fly home.' },
      ]
    },
    localTips: [
      'Verbier is expensive even by Swiss standards — budget at least $200/day for food, drinks, and lift tickets.',
      'The off-piste terrain is world class but should only be skied with a guide after a storm.',
      'Farm Club is the legendary Verbier night spot — if you are into that scene.',
      'The Freeride World Tour stop in January draws the best big mountain riders in the world.',
      'Book accommodation way in advance — Verbier is a small village and fills up fast.',
      'The 4 Vallées lift pass covers Verbier, Nendaz, Veysonnaz, and Thyon — enormous terrain.',
    ],
  },
  {
    slug: 'jackson-hole',
    name: 'Jackson Hole',
    location: 'Wyoming, USA',
    country: 'USA',
    type: 'ski',
    lat: 43.5875,
    lon: -110.8277,
    airportCode: 'JAC',
    flag: '🇺🇸',
    tagline: 'America\'s most legendary big mountain resort',
    description: 'Jackson Hole Mountain Resort has the greatest continuous vertical drop of any US resort at 4,139ft, with notoriously steep terrain and legendary off-piste skiing. The adjacent town of Jackson is one of the coolest mountain towns in America.',
    bestMonths: [12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 320,
    hotelPrice: 160,
    bestRun: 'Corbet\'s Couloir for the brave, Rendezvous Bowl for big mountain powder, Laramie Bowl for intermediate powder.',
    idealConditions: 'Storm cycle dropping 12"+ powder, cold Wyoming temperatures, calm winds',
    weekendTrip: {
      title: 'Jackson Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Jackson Hole (JAC) — one of the most scenic airport approaches in the world. 20min to Teton Village. Million Dollar Cowboy Bar in Jackson town for the vibe.' },
        { day: 'Saturday', plan: 'Aerial tram to the top at 9am. Rendezvous Bowl, then work your way across the mountain. Watch Corbet\'s Couloir from the catwalk.' },
        { day: 'Sunday', plan: 'Apres skiing Cowboys, final laps, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Teton Week',
      days: [
        { day: 'Day 1', plan: 'Arrive JAC, Teton Village base, get sorted.' },
        { day: 'Day 2', plan: 'Top to bottom exploration day — learn the mountain.' },
        { day: 'Day 3', plan: 'Powder day if it snowed — Hobacks and trees in Casper Bowl.' },
        { day: 'Day 4', plan: 'Grand Targhee day trip — other side of the Tetons, incredible snow, no crowds.' },
        { day: 'Day 5', plan: 'Snowmobile tour in Yellowstone — world class experience 1hr from Jackson.' },
        { day: 'Day 6', plan: 'Back to JHMR for your best day — you know the mountain now.' },
        { day: 'Day 7', plan: 'Final morning laps, fly home from JAC.' },
      ]
    },
    localTips: [
      'The aerial tram line can be 45min+ on weekends — get there at 8:30am when the mountain opens.',
      'Corbet\'s Couloir requires a mandatory air and is experts only — watch from the catwalk first.',
      'Grand Targhee on the other side of the range gets more snow and has no crowds — do not skip it.',
      'Jackson town is 20min from the mountain but worth visiting — great bars, restaurants, and Western vibe.',
      'The National Elk Refuge sleigh rides in winter are a great non-ski activity.',
      'Wyoming has no state income tax — Jackson attracts a wealthy crowd but the skiing is for everyone.',
    ],
  },
  {
    slug: 'snapper-rocks',
    name: 'Snapper Rocks',
    location: 'Gold Coast, Australia',
    country: 'Australia',
    type: 'surf',
    lat: -28.1631,
    lon: 153.5500,
    airportCode: 'OOL',
    flag: '🇦🇺',
    tagline: 'The Superbank — the longest pointbreak on earth',
    description: 'Snapper Rocks is the start of the famous Superbank — a sand-bottom pointbreak that can produce rides of over 2 minutes when it links up through Snapper, Greenmount, and Kirra. The Gold Coast is Australia\'s surf capital.',
    bestMonths: [3, 4, 5, 6, 7, 8, 9],
    flightFrom: 'NYC',
    flightPrice: 1100,
    hotelPrice: 80,
    bestBreak: 'Snapper Rocks peak linking through to Kirra on a big cyclone swell — ride for 500m if you are lucky.',
    idealConditions: 'E-NE cyclone swell 4-6ft, light SW offshore winds, low tide',
    weekendTrip: {
      title: 'Gold Coast Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Gold Coast (OOL). Stay in Coolangatta — walking distance to Snapper. Fish and chips on the esplanade.' },
        { day: 'Saturday', plan: 'Dawn patrol Snapper. Walk the pointbreak to check Greenmount and Kirra. Afternoon at Duranbah for beach break.' },
        { day: 'Sunday', plan: 'Morning session, explore Coolangatta town, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Gold Coast Surf Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Gold Coast, settle in Coolangatta.' },
        { day: 'Day 2', plan: 'Full day Superbank — Snapper through to Kirra.' },
        { day: 'Day 3', plan: 'Duranbah beach break — powerful and consistent.' },
        { day: 'Day 4', plan: 'Day trip to Noosa — mellow pointbreak, beautiful national park.' },
        { day: 'Day 5', plan: 'Back to Snapper if swell is still up.' },
        { day: 'Day 6', plan: 'Explore Brisbane — 1hr north, great city.' },
        { day: 'Day 7', plan: 'Final session, fly home.' },
      ]
    },
    localTips: [
      'The Superbank works best on a cyclone swell from the north — check forecasts in summer.',
      'Coolangatta is the best base — cheaper than Surfers Paradise and right on the breaks.',
      'The Kirra end of the bank can produce the most perfect barrels when it all links up.',
      'Australia has excellent cafe culture — great coffee before your dawn patrol.',
    ],
  },
  {
    slug: 'raglan',
    name: 'Raglan',
    location: 'Waikato, New Zealand',
    country: 'New Zealand',
    type: 'surf',
    lat: -37.8000,
    lon: 174.8667,
    airportCode: 'AKL',
    flag: '🇳🇿',
    tagline: 'New Zealand\'s most famous left-hand pointbreak',
    description: 'Raglan is a laid-back surf town on New Zealand\'s west coast that produces one of the Southern Hemisphere\'s best left-hand pointbreaks. Manu Bay and Indicators offer long, walling lefts in a stunning green landscape.',
    bestMonths: [3, 4, 5, 6, 7, 8, 9],
    flightFrom: 'NYC',
    flightPrice: 1300,
    hotelPrice: 70,
    bestBreak: 'Indicators for the longest rides, Manu Bay for the most consistent break, Whale Bay for a more secluded experience.',
    idealConditions: 'SW swell 4-8ft, light NE offshore winds, mid tide',
    weekendTrip: {
      title: 'Raglan Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Auckland (AKL). 2hr drive to Raglan. Stay at a surf lodge overlooking the point.' },
        { day: 'Saturday', plan: 'Dawn patrol Indicators. Walk the point to Manu Bay. Afternoon explore Raglan town.' },
        { day: 'Sunday', plan: 'Morning session Whale Bay — more secluded. Drive back to Auckland, fly home.' },
      ]
    },
    weekTrip: {
      title: 'New Zealand Surf Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Auckland, drive to Raglan.' },
        { day: 'Day 2', plan: 'Full day Indicators and Manu Bay.' },
        { day: 'Day 3', plan: 'Whale Bay and explore the coast south of Raglan.' },
        { day: 'Day 4', plan: 'Rest day — hike the Waikato region, hot springs at Waitomo.' },
        { day: 'Day 5', plan: 'Back to Indicators for another full day.' },
        { day: 'Day 6', plan: 'Drive back to Auckland — explore the city, Waiheke Island.' },
        { day: 'Day 7', plan: 'Final morning, fly home.' },
      ]
    },
    localTips: [
      'Raglan town is small and charming — great cafes, art galleries, and a relaxed vibe.',
      'New Zealand drivers are friendly but roads are narrow — take it easy.',
      'The green hills rolling into the ocean make this one of the most scenic surf destinations on earth.',
      'Bring a wetsuit — water temperatures are cool year round.',
    ],
  },
  {
    slug: 'trestles',
    name: 'Trestles',
    location: 'San Clemente, California',
    country: 'USA',
    type: 'surf',
    lat: 33.3828,
    lon: -117.5897,
    airportCode: 'SNA',
    flag: '🇺🇸',
    tagline: 'Southern California\'s premier performance wave',
    description: 'Trestles is a world-class beach and reef break complex in San Clemente, California. Uppers and Lowers produce powerful, well-shaped waves that have hosted WSL Championship Tour events for decades. A 20-minute walk from the car park makes it feel more remote than it is.',
    bestMonths: [8, 9, 10, 11],
    flightFrom: 'NYC',
    flightPrice: 280,
    hotelPrice: 120,
    bestBreak: 'Lowers for the most performance-oriented waves, Uppers for more power, Church for a quieter option.',
    idealConditions: 'SW swell 4-6ft, light NE Santa Ana winds, low tide',
    weekendTrip: {
      title: 'SoCal Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Orange County (SNA). 30min drive to San Clemente. Stay in town — walkable to everything.' },
        { day: 'Saturday', plan: 'Walk the trail to Lowers at dawn. Full day session. Tacos in San Clemente town.' },
        { day: 'Sunday', plan: 'Morning session Uppers. Drive up the coast to Malibu or Newport Beach. Fly home.' },
      ]
    },
    weekTrip: {
      title: 'California Coast Week',
      days: [
        { day: 'Day 1', plan: 'Arrive SNA, drive to San Clemente.' },
        { day: 'Day 2', plan: 'Full day Trestles — Lowers and Uppers.' },
        { day: 'Day 3', plan: 'Drive south — explore Oceanside and Carlsbad breaks.' },
        { day: 'Day 4', plan: 'Drive north — Huntington Beach, Newport Beach.' },
        { day: 'Day 5', plan: 'Malibu — iconic right-hand pointbreak.' },
        { day: 'Day 6', plan: 'Back to Trestles for a final session.' },
        { day: 'Day 7', plan: 'Fly home from SNA or LAX.' },
      ]
    },
    localTips: [
      'The walk to Trestles is 20 minutes each way — bring a board bag with wheels.',
      'Santa Ana winds blow offshore in autumn — best conditions of the year.',
      'San Clemente is a beautiful small town — great food and relaxed California vibe.',
      'The WSL Surf Ranch is nearby in Lemoore — worth visiting if you are a surf fan.',
    ],
  },
  {
    slug: 'chicama',
    name: 'Chicama',
    location: 'La Libertad, Peru',
    country: 'Peru',
    type: 'surf',
    lat: -7.7000,
    lon: -79.4500,
    airportCode: 'TRU',
    flag: '🇵🇪',
    tagline: 'The longest left-hand wave in the world',
    description: 'Chicama holds the Guinness World Record for the longest surfable wave on earth — up to 4km of rideable left-hand pointbreak on the right swell. Remote, raw, and absolutely unique.',
    bestMonths: [4, 5, 6, 7, 8, 9],
    flightFrom: 'NYC',
    flightPrice: 580,
    hotelPrice: 30,
    bestBreak: 'The main Chicama point — paddle for the sets and ride as far as you can. A boat or mototaxi takes you back up.',
    idealConditions: 'SW swell 6-10ft, light SE offshore winds, mid tide',
    weekendTrip: {
      title: 'Chicama Quick Strike',
      days: [
        { day: 'Friday', plan: 'Fly into Trujillo (TRU). 1.5hr drive to Puerto Malabrigo. Stay at a basic surf hostel.' },
        { day: 'Saturday', plan: 'Full day Chicama — ride as many long ones as you can. Hire a mototaxi to shuttle you back up.' },
        { day: 'Sunday', plan: 'Morning session, drive back to Trujillo, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Peru Surf Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Trujillo, drive to Chicama.' },
        { day: 'Day 2', plan: 'Full day Chicama — experience the longest wave on earth.' },
        { day: 'Day 3', plan: 'Rest day — visit the Chan Chan ruins nearby.' },
        { day: 'Day 4', plan: 'Back to Chicama if swell is holding.' },
        { day: 'Day 5', plan: 'Drive to Huanchaco — traditional reed boat fishermen and beach break.' },
        { day: 'Day 6', plan: 'Explore Trujillo city — colonial architecture and ceviche.' },
        { day: 'Day 7', plan: 'Fly home.' },
      ]
    },
    localTips: [
      'Bring extra fins and leashes — the wave is long and wipeouts happen far from the peak.',
      'The mototaxi shuttle back up the point is part of the experience — negotiate a day rate.',
      'Peru is very affordable — great ceviche and food for next to nothing.',
      'The wave works best at mid to high tide — check local knowledge on arrival.',
    ],
  },
  {
    slug: 'skeleton-bay',
    name: 'Skeleton Bay',
    location: 'Namibia',
    country: 'Namibia',
    type: 'surf',
    lat: -19.1333,
    lon: 12.5833,
    airportCode: 'WDH',
    flag: '🇳🇦',
    tagline: 'The most remote world-class wave on earth',
    description: 'Skeleton Bay in Namibia produces one of the longest, most perfect left-hand barrels in the world — up to 2km of hollow tube in one of the most remote and desolate landscapes imaginable. This is a bucket list mission for serious surfers only.',
    bestMonths: [6, 7, 8, 9],
    flightFrom: 'NYC',
    flightPrice: 1400,
    hotelPrice: 60,
    bestBreak: 'The main Skeleton Bay sandbar — a freight train left that barrels for hundreds of metres. Time it perfectly or watch.',
    idealConditions: 'SW groundswell 6-12ft, strong SE offshore winds, specific sandbar formation',
    weekendTrip: {
      title: 'Skeleton Bay Expedition',
      days: [
        { day: 'Friday', plan: 'Fly into Windhoek (WDH). Domestic flight or long drive to the Skeleton Coast.' },
        { day: 'Saturday', plan: 'Full day at the wave — surf or watch from the beach. The landscape alone is worth the trip.' },
        { day: 'Sunday', plan: 'Morning session, begin the journey home.' },
      ]
    },
    weekTrip: {
      title: 'Namibia Surf Expedition',
      days: [
        { day: 'Day 1', plan: 'Arrive Windhoek, travel to the Skeleton Coast.' },
        { day: 'Day 2', plan: 'First session at Skeleton Bay.' },
        { day: 'Day 3', plan: 'Full day — the wave is fickle, make the most of good conditions.' },
        { day: 'Day 4', plan: 'Explore the Skeleton Coast National Park — seals, shipwrecks, desert.' },
        { day: 'Day 5', plan: 'Back to the wave if conditions hold.' },
        { day: 'Day 6', plan: 'Travel back to Windhoek.' },
        { day: 'Day 7', plan: 'Fly home.' },
      ]
    },
    localTips: [
      'This is a serious expedition — bring everything you need, the nearest town is far away.',
      'The SE wind that makes the wave perfect also makes it freezing — bring a thick wetsuit.',
      'The Benguela Current makes the water cold despite the African latitude — 4/3mm minimum.',
      'The Skeleton Coast is one of the most dramatic landscapes on earth — bring a camera.',
      'This wave requires specific conditions — flexibility in your travel dates is essential.',
    ],
  },
  {
    slug: 'g-land',
    name: "G-Land",
    location: 'East Java, Indonesia',
    country: 'Indonesia',
    type: 'surf',
    lat: -8.6500,
    lon: 114.3500,
    airportCode: 'SUB',
    flag: '🇮🇩',
    tagline: 'The jungle wave — Indonesia\'s most powerful left',
    description: 'G-Land (Grajagan) is a legendary left-hand reef break on the edge of a jungle in East Java. Only accessible by boat or through a surf camp deep in the Alas Purwo National Park. When it fires it is one of the most powerful and perfect waves in Indonesia.',
    bestMonths: [5, 6, 7, 8, 9],
    flightFrom: 'NYC',
    flightPrice: 1050,
    hotelPrice: 150,
    bestBreak: 'Kongs for the longest barrels, Moneytrees for power, Speed Reef for the most intense section.',
    idealConditions: 'SE swell 6-10ft, light NW offshore winds, mid tide',
    weekendTrip: {
      title: 'G-Land Surf Camp',
      days: [
        { day: 'Friday', plan: 'Fly into Surabaya (SUB). Transfer to Banyuwangi, boat across to G-Land camp.' },
        { day: 'Saturday', plan: 'Full day G-Land — multiple sessions, jungle camp food, no distractions.' },
        { day: 'Sunday', plan: 'Morning session, boat back, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Java Jungle Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Surabaya, transfer to G-Land camp.' },
        { day: 'Day 2', plan: 'First full day at G-Land.' },
        { day: 'Day 3', plan: 'Explore all three breaks — Kongs, Moneytrees, Speed Reef.' },
        { day: 'Day 4', plan: 'Jungle walk in Alas Purwo National Park — see monkeys and peacocks.' },
        { day: 'Day 5', plan: 'Back to G-Land for another full day.' },
        { day: 'Day 6', plan: 'Travel back to Surabaya — explore the city.' },
        { day: 'Day 7', plan: 'Fly home.' },
      ]
    },
    localTips: [
      'You must stay at one of the G-Land surf camps — there is no other accommodation.',
      'The camp includes meals — focus entirely on surfing.',
      'Monkeys will steal your food if you leave it unattended — not a joke.',
      'The wave is powerful and unforgiving — intermediate to advanced surfers only.',
      'June-August is the most consistent window — book the camp well in advance.',
    ],
  },
  {
    slug: 'lance-right',
    name: "Lance's Right",
    location: 'Mentawai Islands, Indonesia',
    country: 'Indonesia',
    type: 'surf',
    lat: -3.1333,
    lon: 100.1167,
    airportCode: 'PDG',
    flag: '🇮🇩',
    tagline: 'HT\'s — the most consistent perfect right in the Mentawais',
    description: 'Lance\'s Right (HT\'s) in the Mentawai Islands is widely considered one of the most perfect right-hand reef breaks on earth. Long, hollow, and incredibly consistent — it fires on almost every swell that hits the islands.',
    bestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    flightFrom: 'NYC',
    flightPrice: 1200,
    hotelPrice: 180,
    bestBreak: 'The main HT\'s peak — a long, fast right that barrels through multiple sections. Can link up for 200m+ rides.',
    idealConditions: 'SW swell 4-8ft, light E trades, mid tide',
    weekendTrip: {
      title: 'Mentawai Charter',
      days: [
        { day: 'Friday', plan: 'Fly into Padang (PDG). Board surf charter boat, sail overnight.' },
        { day: 'Saturday', plan: 'Full day HT\'s — dawn to dusk sessions.' },
        { day: 'Sunday', plan: 'Morning session, sail back to Padang, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Mentawai Islands Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Padang, board charter.' },
        { day: 'Day 2', plan: 'HT\'s all day.' },
        { day: 'Day 3', plan: 'Macaronis — the playful left nearby.' },
        { day: 'Day 4', plan: 'Chase swell across the islands.' },
        { day: 'Day 5', plan: 'Kandui or Rifles.' },
        { day: 'Day 6', plan: 'Final full day at HT\'s.' },
        { day: 'Day 7', plan: 'Sail back, fly home.' },
      ]
    },
    localTips: [
      'A surf charter is the only way — book through a reputable Padang operator.',
      'HT\'s works on almost any swell direction — the most consistent spot in the islands.',
      'Bring a quiver — you will want different boards for different conditions.',
      'The water is crystal clear and warm — one of the most beautiful places on earth.',
    ],
  },
  {
    slug: 'nazare',
    name: 'Nazaré',
    location: 'Centro, Portugal',
    country: 'Portugal',
    type: 'surf',
    lat: 39.6011,
    lon: -9.0700,
    airportCode: 'LIS',
    flag: '🇵🇹',
    tagline: 'The biggest waves ever surfed — tow-in big wave paradise',
    description: 'Nazaré is where the biggest waves ever surfed have been recorded — thanks to a unique underwater canyon that amplifies Atlantic swells into 80ft+ monsters. A spectator destination as much as a surf destination.',
    bestMonths: [10, 11, 12, 1, 2],
    flightFrom: 'NYC',
    flightPrice: 480,
    hotelPrice: 65,
    bestBreak: 'Praia do Norte for the giant tow-in waves — watch from the fort. Praia de Nazaré for more manageable beach break.',
    idealConditions: 'NW groundswell 20ft+, strong N winds, specific canyon alignment',
    weekendTrip: {
      title: 'Nazaré Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Lisbon (LIS). 1.5hr drive to Nazaré. Stay in the old town.' },
        { day: 'Saturday', plan: 'Watch from the Forte de São Miguel Arcanjo if it is big. Surf the beach break if it is manageable. Fresh seafood dinner.' },
        { day: 'Sunday', plan: 'Morning at the fort, drive back to Lisbon, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Portuguese Atlantic Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Lisbon, drive to Nazaré.' },
        { day: 'Day 2', plan: 'Big wave watch or beach break surf.' },
        { day: 'Day 3', plan: 'Drive to Peniche — Supertubos world class beach break.' },
        { day: 'Day 4', plan: 'Ericeira — UNESCO world surfing reserve.' },
        { day: 'Day 5', plan: 'Back to Nazaré if another swell is forecast.' },
        { day: 'Day 6', plan: 'Explore Lisbon — one of Europe\'s best cities.' },
        { day: 'Day 7', plan: 'Fly home.' },
      ]
    },
    localTips: [
      'The big wave season is October to February — check the forecast obsessively.',
      'The fort viewpoint is free and gives you the best view of the giant waves.',
      'Nazaré town is charming — dried fish hanging from windows, traditional fishing culture.',
      'Combine with Peniche and Ericeira for a full Portuguese surf road trip.',
    ],
  },
  {
    slug: 'courchevel',
    name: 'Courchevel',
    location: 'Savoie, France',
    country: 'France',
    type: 'ski',
    lat: 45.4154,
    lon: 6.6340,
    airportCode: 'GVA',
    flag: '🇫🇷',
    tagline: 'The crown jewel of the French Alps',
    description: 'Courchevel is the most glamorous ski resort in France and part of the massive Les 3 Vallées ski area — the largest linked ski area in the world. World-class terrain, Michelin-starred restaurants, and an iconic altiport make this a bucket list destination.',
    bestMonths: [1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 680,
    hotelPrice: 220,
    bestRun: 'La Croisette for the main bowl, Saulire for off-piste, the connection to Méribel for big mountain touring.',
    idealConditions: 'Fresh powder, cold temperatures, clear skies over the 3 Vallées',
    weekendTrip: {
      title: 'Courchevel Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Geneva (GVA). Transfer to Courchevel 1850. Check into a chalet. Savoyard dinner — tartiflette and vin chaud.' },
        { day: 'Saturday', plan: 'Full day skiing the 3 Vallées — Courchevel to Méribel to Val Thorens. Lunch at a mountain restaurant.' },
        { day: 'Sunday', plan: 'Morning laps above Courchevel 1850. Transfer to Geneva, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Les 3 Vallées Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Geneva, transfer to Courchevel.' },
        { day: 'Day 2', plan: 'Explore Courchevel — La Croisette and Saulire.' },
        { day: 'Day 3', plan: 'Ski across to Méribel — different feel, great terrain.' },
        { day: 'Day 4', plan: 'Push on to Val Thorens — highest resort in the Alps.' },
        { day: 'Day 5', plan: 'Powder day — wherever it snowed most overnight.' },
        { day: 'Day 6', plan: 'La Tania and Saint-Martin — quieter villages in the valley.' },
        { day: 'Day 7', plan: 'Final morning, transfer to Geneva, fly home.' },
      ]
    },
    localTips: [
      'Courchevel 1850 is the most expensive — Courchevel 1650 and 1550 are cheaper and connected by lift.',
      'The Les 3 Vallées lift pass covers 600km of pistes — the largest ski area in the world.',
      'Val Thorens at the top of the valley has the most reliable snow — go there on marginal days.',
      'Book mountain restaurants in advance — the good ones fill up fast.',
    ],
  },
  {
    slug: 'val-disere',
    name: "Val d'Isère",
    location: 'Savoie, France',
    country: 'France',
    type: 'ski',
    lat: 45.4480,
    lon: 6.9800,
    airportCode: 'GVA',
    flag: '🇫🇷',
    tagline: 'Espace Killy — one of the greatest ski areas in the Alps',
    description: "Val d'Isère is one of France's most iconic high-altitude ski resorts, linked with Tignes to form the massive Espace Killy ski area. Glacier skiing ensures snow from November to May, and the off-piste terrain is world class.",
    bestMonths: [12, 1, 2, 3, 4],
    flightFrom: 'NYC',
    flightPrice: 660,
    hotelPrice: 160,
    bestRun: 'La Face for the famous downhill run, Bellevarde for big mountain feel, the glacier at Pisaillas for spring skiing.',
    idealConditions: 'Fresh powder after a storm, cold high-altitude temperatures, light winds',
    weekendTrip: {
      title: "Val d'Isère Weekend",
      days: [
        { day: 'Friday', plan: "Fly into Geneva (GVA). Transfer to Val d'Isère (2.5hrs). Check in, vin chaud on arrival." },
        { day: 'Saturday', plan: 'Bellevarde gondola at 9am. Ski La Face — the famous World Cup downhill. Afternoon on the glacier.' },
        { day: 'Sunday', plan: 'Morning laps, transfer to Geneva, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Espace Killy Week',
      days: [
        { day: 'Day 1', plan: "Arrive Geneva, transfer to Val d'Isère." },
        { day: 'Day 2', plan: "Explore Val d'Isère — Bellevarde and Solaise sectors." },
        { day: 'Day 3', plan: 'Ski across to Tignes — glacier and big terrain.' },
        { day: 'Day 4', plan: 'Off-piste day with a guide in the Fornet sector.' },
        { day: 'Day 5', plan: 'Powder day — wherever it snowed overnight.' },
        { day: 'Day 6', plan: "Val d'Isère town — great restaurants and shops." },
        { day: 'Day 7', plan: 'Final morning, fly home.' },
      ]
    },
    localTips: [
      "Val d'Isère sits at 1850m — the glacier at 3300m means reliable snow all season.",
      'La Face is the famous Hahnenkamm-style downhill — ski it on a clear day.',
      'Tignes is connected and has a different, more functional vibe — great snow though.',
      'April is underrated — spring snow, fewer crowds, and the glacier is still open.',
    ],
  },
  {
    slug: 'banff',
    name: 'Banff & Lake Louise',
    location: 'Alberta, Canada',
    country: 'Canada',
    type: 'ski',
    lat: 51.4968,
    lon: -115.9281,
    airportCode: 'YYC',
    flag: '🇨🇦',
    tagline: 'Skiing in the Canadian Rockies — scenery unlike anywhere else',
    description: 'The Banff area combines three world-class ski resorts — Banff Sunshine, Lake Louise, and Mt Norquay — with the most dramatic mountain scenery in North America. The turquoise lakes, elk on the road, and Rocky Mountain powder make this a truly special destination.',
    bestMonths: [12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 380,
    hotelPrice: 150,
    bestRun: 'Lake Louise Back Bowls for powder, Delirium Dive at Sunshine for experts, Banff town for après.',
    idealConditions: 'Alberta clipper storm dropping powder, cold Rocky Mountain temperatures',
    weekendTrip: {
      title: 'Banff Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Calgary (YYC). 90min drive to Banff. Stay in Banff town. Elk Street dinner.' },
        { day: 'Saturday', plan: 'Lake Louise — ski the front face then explore the Back Bowls. Drive past the frozen lake.' },
        { day: 'Sunday', plan: 'Banff Sunshine — different resort, great snow. Drive back to Calgary, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Canadian Rockies Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Calgary, drive to Banff.' },
        { day: 'Day 2', plan: 'Lake Louise — iconic views and massive terrain.' },
        { day: 'Day 3', plan: 'Banff Sunshine — highest base elevation in Canada.' },
        { day: 'Day 4', plan: 'Mt Norquay — smaller, quieter, great for a relaxed day.' },
        { day: 'Day 5', plan: 'Powder day at whichever resort got the most snow.' },
        { day: 'Day 6', plan: 'Explore Banff town — hot springs, wildlife, stunning scenery.' },
        { day: 'Day 7', plan: 'Final morning, drive to Calgary, fly home.' },
      ]
    },
    localTips: [
      'The Tri-Area lift pass covers all three resorts — excellent value.',
      'Elk wander through Banff town — they have the right of way.',
      'The Banff hot springs after skiing are a must — views of the Rockies while you soak.',
      'Lake Louise is 45min from Banff town — stay in Banff for more restaurant options.',
      'Alberta gets very cold — dress in proper layers, especially for the Back Bowls.',
    ],
  },
  {
    slug: 'telluride',
    name: 'Telluride',
    location: 'Colorado, USA',
    country: 'USA',
    type: 'ski',
    lat: 37.9375,
    lon: -107.8123,
    airportCode: 'TEX',
    flag: '🇺🇸',
    tagline: 'Colorado\'s most beautiful and remote ski town',
    description: 'Telluride sits in a stunning box canyon in the San Juan Mountains of Colorado. One of the most beautiful ski towns in America — a historic Victorian mining town with world-class terrain and Colorado\'s champagne powder.',
    bestMonths: [12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 420,
    hotelPrice: 180,
    bestRun: 'Plunge for the steepest groomed run, Gold Hill for off-piste, the Revelation Bowl for powder days.',
    idealConditions: 'San Juan storm cycle dropping powder, cold Colorado temperatures, light winds',
    weekendTrip: {
      title: 'Telluride Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Telluride (TEX) or Montrose (MTJ). Stay in Telluride town or Mountain Village. Dinner on Colorado Ave.' },
        { day: 'Saturday', plan: 'Full day skiing — Plunge, Spiral Staircase, Revelation Bowl. Ride the free gondola between town and Mountain Village.' },
        { day: 'Sunday', plan: 'Morning laps, fly home.' },
      ]
    },
    weekTrip: {
      title: 'San Juan Mountains Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Telluride, explore the historic town.' },
        { day: 'Day 2', plan: 'Learn the mountain — front face and Prospect Bowl.' },
        { day: 'Day 3', plan: 'Powder day — Gold Hill and Revelation Bowl.' },
        { day: 'Day 4', plan: 'Guided backcountry tour in the San Juans.' },
        { day: 'Day 5', plan: 'Rest day — snowshoe to Bridal Veil Falls.' },
        { day: 'Day 6', plan: 'Final full day — best runs of the trip.' },
        { day: 'Day 7', plan: 'Fly home.' },
      ]
    },
    localTips: [
      'The free gondola connecting Telluride town and Mountain Village is a genius piece of infrastructure — use it.',
      'Telluride gets more snow than most Colorado resorts due to its position in the San Juans.',
      'The town is small and walkable — everything is on Colorado Avenue.',
      'Book flights early — Telluride airport is small and routes fill up fast.',
    ],
  },
  {
    slug: 'mammoth',
    name: 'Mammoth Mountain',
    location: 'California, USA',
    country: 'USA',
    type: 'ski',
    lat: 37.6308,
    lon: -119.0326,
    airportCode: 'MMH',
    flag: '🇺🇸',
    tagline: 'California\'s biggest ski mountain — epic terrain and long season',
    description: 'Mammoth Mountain is California\'s premier ski destination — a massive volcano in the Eastern Sierra with over 3,500 acres of terrain, a summit at 11,053ft, and one of the longest ski seasons in North America often running into June.',
    bestMonths: [12, 1, 2, 3, 4, 5],
    flightFrom: 'NYC',
    flightPrice: 380,
    hotelPrice: 130,
    bestRun: 'Cornice Bowl for powder, Lincoln Mountain for steeps, Broadway for long groomed runs.',
    idealConditions: 'Sierra storm cycle dropping heavy snow, cold temperatures, light winds on the upper mountain',
    weekendTrip: {
      title: 'Mammoth Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Mammoth Lakes (MMH) or drive from LA (5hrs). Stay in Mammoth Lakes town. Dinner at Toomey\'s.' },
        { day: 'Saturday', plan: 'Gondola to the top at 9am. Cornice Bowl and Lincoln Mountain. Après at Mammoth Mountain Inn.' },
        { day: 'Sunday', plan: 'Morning laps, drive or fly back.' },
      ]
    },
    weekTrip: {
      title: 'Eastern Sierra Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Mammoth Lakes.' },
        { day: 'Day 2', plan: 'Explore the main mountain — 28 lifts of terrain.' },
        { day: 'Day 3', plan: 'Powder day — Cornice Bowl and the backside.' },
        { day: 'Day 4', plan: 'Drive to June Mountain — smaller, quieter, same Epic Pass.' },
        { day: 'Day 5', plan: 'Hot Creek Geological Site — natural hot springs.' },
        { day: 'Day 6', plan: 'Final full day at Mammoth.' },
        { day: 'Day 7', plan: 'Drive or fly home.' },
      ]
    },
    localTips: [
      'Mammoth gets enormous snowfall — sometimes 400+ inches per season.',
      'The season can run until June or even July in big snow years.',
      'LA skiers crowd the mountain on weekends — go midweek if possible.',
      'The drive from LA through the Owens Valley is stunning — worth the road trip.',
    ],
  },
  {
    slug: 'hakuba',
    name: 'Hakuba Valley',
    location: 'Nagano, Japan',
    country: 'Japan',
    type: 'ski',
    lat: 36.6983,
    lon: 137.8600,
    airportCode: 'ITM',
    flag: '🇯🇵',
    tagline: 'Olympic powder — Japan\'s most international ski destination',
    description: 'Hakuba Valley in Nagano hosted the 1998 Winter Olympics and contains 10 interconnected ski resorts with some of the best powder snow in Japan. More international than Niseko but equally impressive snow and terrain.',
    bestMonths: [12, 1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 750,
    hotelPrice: 100,
    bestRun: 'Happo One for the Olympic downhill course, Tsugaike for powder and off-piste, Goryu for tree runs.',
    idealConditions: 'Siberian storm cycle, temperatures below -5°C, overnight snowfall',
    weekendTrip: {
      title: 'Hakuba Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Osaka (ITM) or Tokyo (NRT). Train or bus to Hakuba (3-4hrs). Ramen on arrival.' },
        { day: 'Saturday', plan: 'Happo One — the main resort, Olympic terrain. Onsen at the hotel.' },
        { day: 'Sunday', plan: 'Goryu or Tsugaike for tree runs. Head back to the city.' },
      ]
    },
    weekTrip: {
      title: 'Nagano Ski Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Hakuba, get settled.' },
        { day: 'Day 2', plan: 'Happo One — biggest resort in the valley.' },
        { day: 'Day 3', plan: 'Goryu and Escal Plaza — great tree runs.' },
        { day: 'Day 4', plan: 'Tsugaike — more remote, incredible off-piste.' },
        { day: 'Day 5', plan: 'Powder day — chase the best overnight snowfall.' },
        { day: 'Day 6', plan: 'Day trip to Matsumoto — historic castle city.' },
        { day: 'Day 7', plan: 'Final morning laps, travel home.' },
      ]
    },
    localTips: [
      'Hakuba is more international than Niseko — easier to navigate for first-time Japan visitors.',
      'The Hakuba Valley pass covers all 10 resorts — great value.',
      'Happo One hosted the 1998 Olympic downhill — ski the course on a clear day.',
      'The village has excellent western food alongside traditional Japanese options.',
    ],
  },
  {
    slug: 'cortina',
    name: "Cortina d'Ampezzo",
    location: 'Veneto, Italy',
    country: 'Italy',
    type: 'ski',
    lat: 46.5362,
    lon: 12.1356,
    airportCode: 'VCE',
    flag: '🇮🇹',
    tagline: 'The queen of the Dolomites — skiing in a UNESCO world heritage landscape',
    description: "Cortina d'Ampezzo is Italy's most glamorous ski resort, set in the stunning pink-tinged Dolomite mountains. Host of the 2026 Winter Olympics, Cortina combines world-class skiing with Italian style, incredible food, and one of the most dramatic mountain landscapes on earth.",
    bestMonths: [1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 720,
    hotelPrice: 160,
    bestRun: 'Tofana for the Olympic downhill, Cristallo for panoramic views, the Dolomiti Superski connection for endless terrain.',
    idealConditions: 'Fresh snow on the Dolomites, cold temperatures, clear skies for the views',
    weekendTrip: {
      title: 'Cortina Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Venice (VCE). 2hr drive to Cortina. Aperitivo on the Corso Italia — the most stylish street in ski resort history.' },
        { day: 'Saturday', plan: 'Tofana cable car to the top. Ski the Olympic downhill. Lunch with views of the Dolomites. Faloria in the afternoon.' },
        { day: 'Sunday', plan: 'Morning laps, drive back to Venice, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Dolomites Ski Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Venice, drive to Cortina.' },
        { day: 'Day 2', plan: 'Tofana and the Olympic runs.' },
        { day: 'Day 3', plan: 'Cristallo — stunning views of the Dolomites.' },
        { day: 'Day 4', plan: 'Day trip to Alta Badia — part of the Dolomiti Superski area.' },
        { day: 'Day 5', plan: 'Cinque Torri — ancient rock towers with ski runs between them.' },
        { day: 'Day 6', plan: 'Final full day — best runs and a long lunch.' },
        { day: 'Day 7', plan: 'Drive to Venice, fly home.' },
      ]
    },
    localTips: [
      'The Dolomites turn pink at sunset — one of the most beautiful sights in the world.',
      'Italian ski culture means long lunches on the mountain — embrace it.',
      'Cortina is hosting the 2026 Winter Olympics — infrastructure is being upgraded.',
      'The Dolomiti Superski pass covers 1,200km of pistes across 12 resorts.',
      'Venice is only 2hrs away — combine skiing with a Venice city break.',
    ],
  },
  {
    slug: 'les-trois-vallees',
    name: 'Les 3 Vallées',
    location: 'Savoie, France',
    country: 'France',
    type: 'ski',
    lat: 45.3667,
    lon: 6.5833,
    airportCode: 'GVA',
    flag: '🇫🇷',
    tagline: 'The largest ski area in the world — 600km of pistes',
    description: 'Les 3 Vallées is the largest linked ski area in the world, connecting Courchevel, Méribel, Val Thorens, and several smaller resorts across three valleys and 600km of pistes. A week is barely enough to scratch the surface.',
    bestMonths: [1, 2, 3],
    flightFrom: 'NYC',
    flightPrice: 670,
    hotelPrice: 170,
    bestRun: 'The descent from Cime Caron at Val Thorens, the Méribel valley runs, Courchevel\'s La Croisette bowl.',
    idealConditions: 'Fresh powder across all three valleys, cold temperatures, clear skies',
    weekendTrip: {
      title: '3 Vallées Weekend',
      days: [
        { day: 'Friday', plan: 'Fly into Geneva (GVA). Transfer to Méribel — central location for all three valleys. Raclette dinner.' },
        { day: 'Saturday', plan: 'Ski from Méribel to Courchevel in the morning, Val Thorens in the afternoon — three resorts in one day.' },
        { day: 'Sunday', plan: 'Morning laps in Méribel, transfer to Geneva, fly home.' },
      ]
    },
    weekTrip: {
      title: 'Three Valleys Full Week',
      days: [
        { day: 'Day 1', plan: 'Arrive Geneva, transfer to Méribel.' },
        { day: 'Day 2', plan: 'Méribel — explore the home valley.' },
        { day: 'Day 3', plan: 'Courchevel — ski the famous 1850 area.' },
        { day: 'Day 4', plan: 'Val Thorens — highest resort in the Alps, most reliable snow.' },
        { day: 'Day 5', plan: 'Les Menuires and Saint-Martin — quieter villages.' },
        { day: 'Day 6', plan: 'Powder day — chase the best snow across all three valleys.' },
        { day: 'Day 7', plan: 'Final morning, transfer to Geneva, fly home.' },
      ]
    },
    localTips: [
      'Stay in Méribel for the most central access to all three valleys.',
      'Val Thorens at 2300m has the most reliable snow — go there when conditions are marginal lower down.',
      'The 3 Vallées lift pass is expensive but covers more skiing than anywhere else on earth.',
      'You genuinely need a week to explore this area properly — a weekend barely scratches the surface.',
    ],
  },
  {
    slug: "bells-beach",
    name: "Bells Beach",
    location: "Torquay, Victoria, Australia",
    country: "Australia",
    type: "surf",
    lat: -38.3686,
    lon: 144.2828,
    airportCode: "MEL",
    flag: "🇦🇺",
    tagline: "Australia's most iconic point break and home of the Rip Curl Pro",
    description: "Bells Beach is the spiritual home of Australian surfing, hosting the world's longest-running surf competition since 1961. This powerful right-hand point break delivers world-class waves along the dramatic clifftop coastline of Victoria's Surf Coast.",
    bestMonths: [3, 4, 5, 6, 7, 8],
    flightFrom: "NYC",
    flightPrice: 1200,
    hotelPrice: 150,
    bestBreak: "The Bells Bowl is the main attraction - a long, powerful right-hander that breaks over a rock shelf. Take off at the top of the point near the rock platform and pump through the bowl section.",
    idealConditions: "Large Southern Ocean swells from 4-8 feet with light offshore northerly winds. Best on mid to high tide.",
    idealSwellDirection: 225,
    idealWindDirection: 360,
    weekendTrip: {
      title: "Bells Beach Easter Weekend",
      days: [
        { day: "Friday", plan: "Fly into Melbourne and drive 90 minutes to Torquay. Afternoon session at Bells or Winki Pop. Dinner at Bomboras Torquay." },
        { day: "Saturday", plan: "Dawn patrol at Bells Beach. Explore the Surf Coast Walk. Visit the Australian National Surfing Museum. Evening at Jan Juc." },
        { day: "Sunday", plan: "Early surf at Winki Pop or Bells. Drive the Great Ocean Road. Stop at the Rip Curl flagship store before flying home." },
      ]
    },
    weekTrip: {
      title: "Ultimate Surf Coast Adventure",
      days: [
        { day: "Day 1", plan: "Arrive Melbourne, drive to Torquay. Afternoon surf at Bells. Sunset dinner at The Sands Torquay." },
        { day: "Day 2", plan: "Dawn session at Bells. Visit Australian National Surfing Museum. Afternoon at Winki Pop." },
        { day: "Day 3", plan: "Surf Bells then walk the Surf Coast Walk to Winki Pop. Drive to Lorne for dinner." },
        { day: "Day 4", plan: "Morning surf at Lorne point. Explore Erskine Falls. Drive to Apollo Bay." },
        { day: "Day 5", plan: "Surf Apollo Bay at dawn. Drive to see the Twelve Apostles. Return to Torquay." },
        { day: "Day 6", plan: "Full day at Bells Beach. Multiple sessions if swell is pumping. Celebratory dinner at Growlers." },
        { day: "Day 7", plan: "Sunrise final session at Bells. Breakfast at Blackman's Coffee. Drive back to Melbourne. Fly home." },
      ]
    },
    localTips: [
      "Respect the locals — Bells has a strong local crew. Wait your turn and don't snake waves.",
      "Check the Bells webcam before heading out — conditions can change rapidly.",
      "Bring a 3/2mm or 4/3mm wetsuit year-round — Victorian water is cold.",
      "The rock shelf can be treacherous — enter and exit carefully at the channel near the stairs.",
      "If Bells is too crowded check Winki Pop, Centreside, or Jan Juc nearby.",
    ],
  },
  {
    slug: "la-grave-france",
    name: "La Grave",
    location: "La Grave, French Alps",
    country: "France",
    type: "ski",
    lat: 45.0442,
    lon: 6.3078,
    airportCode: "GNB",
    flag: "🇫🇷",
    tagline: "The ultimate off-piste adventure for expert skiers only",
    description: "La Grave is a legendary freeride destination offering 2,150 meters of vertical descent without a single groomed run. This raw, unpatrolled mountain terrain attracts expert skiers and snowboarders seeking the ultimate backcountry experience accessible by lift.",
    bestMonths: [1, 2, 3],
    flightFrom: "NYC",
    flightPrice: 650,
    hotelPrice: 120,
    bestRun: "The Vallons de la Meije — a full descent from 3,200m through glacier terrain, exposed ridges and technical couloirs to the valley floor at 1,450m.",
    idealConditions: "Fresh powder on a stable snowpack, cold temperatures, recent 20-40cm snowfall on north-facing aspects",
    weekendTrip: {
      title: "Expert Weekend at La Grave",
      days: [
        { day: "Friday", plan: "Fly into Grenoble (GNB), 90min drive to La Grave. Meet your guide, organize avalanche gear, prepare for the weekend." },
        { day: "Saturday", plan: "Full La Grave descent from the top station with your guide. Ski the Vallons de la Meije, Chancel and Trifides couloirs. Multiple laps if conditions allow." },
        { day: "Sunday", plan: "Explore the Combe de Rachasse or Girose glacier. Afternoon drive back to Grenoble for evening flights." },
      ]
    },
    weekTrip: {
      title: "Ultimate La Grave Freeride Week",
      days: [
        { day: "Day 1", plan: "Arrive Grenoble, transfer to La Grave. Avalanche safety briefing, gear check, introductory run to assess conditions." },
        { day: "Day 2", plan: "Full descent via the classic Vallons route. Practice terrain reading through the upper glacier. Multiple laps if energy allows." },
        { day: "Day 3", plan: "East-facing lines off P2 — Pyramide couloirs and Grand Sablat. Different snow conditions and spectacular views of La Meije." },
        { day: "Day 4", plan: "Ski touring to the Girose glacier or traverse to St. Christophe. Pack lunch on the mountain." },
        { day: "Day 5", plan: "Technical couloirs day — Trifides, Banane, or Oratoire depending on conditions." },
        { day: "Day 6", plan: "Peyrolle sector for tree skiing if weather deteriorates. Celebratory dinner with your guide group." },
        { day: "Day 7", plan: "Final morning session. Drive back to Grenoble. Stop at Bourg d'Oisans for lunch before afternoon flights." },
      ]
    },
    localTips: [
      "Hiring a certified guide is essential — the mountain is unpatrolled, unmarked, with serious hazards including crevasses and avalanche terrain.",
      "The telepherique only has two stations — you are committed to long descents with no bail-out options.",
      "Book guides and accommodation well in advance — La Grave has very limited lodging capacity.",
      "The village has limited amenities — bring specialized gear from Grenoble or Bourg d'Oisans.",
      "Check weather and avalanche conditions obsessively — the lift often doesn't run due to wind.",
    ],
  },
  {
    slug: "cape-hatteras",
    name: "Cape Hatteras",
    location: "Outer Banks, North Carolina",
    country: "USA",
    type: "surf",
    lat: 35.2269,
    lon: -75.5494,
    airportCode: "ORF",
    flag: "🇺🇸",
    tagline: "The Graveyard of the Atlantic delivers world-class sandbars and hurricane swells",
    description: "Cape Hatteras is the crown jewel of East Coast surfing, jutting 30 miles into the Atlantic where warm Gulf Stream waters meet cold Labrador currents. This exposed barrier island catches more swell than anywhere on the Eastern Seaboard, producing powerful beach breaks and legendary waves around the lighthouse.",
    bestMonths: [8, 9, 10, 11],
    flightFrom: "NYC",
    flightPrice: 250,
    hotelPrice: 120,
    bestBreak: "The Lighthouse area near Cape Point — shifting sandbars create powerful A-frame peaks. Paddle through the channel, position on the peak, and expect steep drops into barreling sections.",
    idealConditions: "Hurricane or nor'easter groundswell 4-8ft, light offshore winds, hollow sandbars",
    idealSwellDirection: 90,
    idealWindDirection: 270,
    weekendTrip: {
      title: "Hurricane Swell Weekend",
      days: [
        { day: "Friday", plan: "Fly into Norfolk (ORF), 2hr drive to Buxton. Scout conditions at the Lighthouse. Evening session at S-Turns if swell is building. Fresh seafood at Diamond Shoals Restaurant." },
        { day: "Saturday", plan: "Dawn patrol at the Lighthouse for morning offshore winds. Breakfast at Orange Blossom Bakery. Rest midday, check Frisco Pier or Old Lighthouse Beach. Late afternoon session at whatever is firing." },
        { day: "Sunday", plan: "Early session at Cape Point if conditions hold. Explore Rodanthe Pier for variety. Pack up noon, final lunch at Rusty's Surf and Turf, drive back to Norfolk." },
      ]
    },
    weekTrip: {
      title: "Ultimate Outer Banks Surf Safari",
      days: [
        { day: "Day 1", plan: "Arrive Norfolk, drive to Nags Head. Afternoon session at Jennette's Pier. Dinner at Sam and Omie's." },
        { day: "Day 2", plan: "Morning surf Nags Head dunes, drive south to Pea Island, surf Rodanthe Pier area." },
        { day: "Day 3", plan: "Dawn session at S-Turns in Salvo. Drive to Buxton, surf the Lighthouse all afternoon." },
        { day: "Day 4", plan: "Full day Cape Point — arrive early for parking. Multiple sessions as sandbars shift. Bring lunch." },
        { day: "Day 5", plan: "Explore Hatteras Village south-facing beaches. Visit the Graveyard of the Atlantic Museum." },
        { day: "Day 6", plan: "Ferry to Ocracoke Island. Surf uncrowded beach breaks. Return on evening ferry." },
        { day: "Day 7", plan: "Final dawn patrol at the Lighthouse. Drive north checking Avon Pier, Salvo, Rodanthe. Fly home from Norfolk." },
      ]
    },
    localTips: [
      "Cape Point requires a 4WD vehicle with beach driving permit — air tires down to 15-20 PSI.",
      "Sandbars shift constantly after big swells — be prepared to move around to find the best banks.",
      "Peak hurricane season August-October brings the biggest swells — weekdays are much less crowded.",
      "Water temps range from 50s in winter to 80s in summer — 3/2mm wetsuit in fall and spring.",
      "Respect the locals who surf here year-round — follow lineup etiquette and be friendly.",
    ],
  },
  {
    slug: 'alyeska-alaska',
    name: 'Alyeska Resort',
    location: 'Girdwood, Alaska',
    country: 'USA',
    type: 'ski',
    lat: 60.9606,
    lon: -149.0994,
    airportCode: 'ANC',
    flag: '🇺🇸',
    tagline: 'Legendary powder and ocean views in America\'s Last Frontier',
    description: 'Alyeska Resort offers an unparalleled Alaskan skiing experience with over 1,600 acres of terrain and jaw-dropping views of the Chugach Mountains and Turnagain Arm. Known for epic snowfall averaging 669 inches annually, this destination combines world-class steep skiing, expansive backcountry access, and the unique experience of skiing with the ocean visible below. The resort\'s dramatic 2,500-foot vertical drop and legendary spring skiing extend the season well into May.',
    bestMonths: [2, 3, 4],
    flightFrom: 'NYC',
    flightPrice: 450,
    hotelPrice: 280,
    bestRun: 'North Face offers expert-level terrain with steep chutes, gladed tree skiing, and consistently deep powder. Access it via the Summit Tram to 3,939 feet, then drop into runs like High Traverse or Wedding Bowl for untracked pow and technical challenges requiring strong avalanche awareness.',
    idealConditions: 'Fresh snowfall of 6-12 inches on a stable base, clear or partly cloudy skies for visibility, and temperatures between 15-25°F. Spring corn snow conditions in April-May with extended daylight hours.',
    weekendTrip: {
      title: 'Powder Weekend in the Chugach',
      days: [
        {
          day: 'Friday',
          plan: 'Fly into Anchorage and drive 40 minutes south on Seward Highway to Girdwood. Check into Alyeska Resort or a local lodge. Grab dinner at Jack Sprat in Girdwood and rest up for early mountain access.',
        },
        {
          day: 'Saturday',
          plan: 'First tram up at 10:30 AM to beat crowds to fresh powder on North Face. Ski hard until 2 PM, break for lunch at Seven Glaciers Restaurant accessed via tram. Afternoon laps on Headwall and Christmas Bowl. Evening soak in hotel hot tub and dinner at The Bake Shop.',
        },
        {
          day: 'Sunday',
          plan: 'Early morning powder hunt on backside terrain. Explore tree runs off Glacier Bowl Chair. Depart by 2 PM for scenic drive back to Anchorage, stopping at Beluga Point for wildlife viewing. Evening flight home or extend in Anchorage.',
        },
      ],
    },
    weekTrip: {
      title: 'Ultimate Alaska Ski Adventure',
      days: [
        {
          day: 'Day 1',
          plan: 'Arrive in Anchorage, pick up rental car, and drive to Girdwood. Check into accommodations, explore the village, get fitted for gear if needed. Sunset dinner at Double Musky Inn (reservations required).',
        },
        {
          day: 'Day 2',
          plan: 'First full day on mountain. Orient yourself with groomers on Chairs 3 and 4, then progress to intermediate terrain. Take the Aerial Tram for lunch and panoramic views. Afternoon exploration of tree runs and gladed areas.',
        },
        {
          day: 'Day 3',
          plan: 'Advanced terrain day - North Face via tram, hit High Traverse, Headwall, and expert chutes. Hire a guide for backcountry gates if conditions permit. Pack lunch to maximize powder time. Evening aurora viewing if clear.',
        },
        {
          day: 'Day 4',
          plan: 'Cat skiing day trip with Chugach Powder Guides for untracked backcountry terrain and huge vertical. Full day guided experience with lunch included. Return exhausted but exhilarated for casual dinner in village.',
        },
        {
          day: 'Day 5',
          plan: 'Recovery day with mellow morning runs, spa treatment at resort. Afternoon excursion to Portage Glacier or Alaska Wildlife Conservation Center. Evening at Girdwood Brewing Company.',
        },
        {
          day: 'Day 6',
          plan: 'Spring skiing focus - sleep in, hit the slopes at 11 AM for perfect corn snow conditions. Ski until 5 PM with extended daylight. Consider heli-skiing add-on if budget allows. Farewell dinner at Seven Glaciers.',
        },
        {
          day: 'Day 7',
          plan: 'Final morning runs on favorite terrain. Depart mountain by noon, scenic drive to Anchorage with stops at Beluga Point and Bird Point. Visit Anchorage Museum if time permits before evening departure.',
        },
      ],
    },
    localTips: [
      'The Aerial Tram doesn\'t start until 10:30 AM, so sleep in or warm up on lower mountain chairs first - no need for dawn patrol here.',
      'Spring skiing (April-May) offers the best weather, longest days, and amazing corn snow - often better than midwinter conditions with better visibility.',
      'Rent avalanche gear and consider hiring a guide for backcountry gates - the terrain is serious and weather can change rapidly in the Chugach.',
      'Drive the Seward Highway carefully, especially in winter - it\'s spectacularly scenic but watch for ice, moose, and Dall sheep on the road.',
      'Book Seven Glaciers restaurant for lunch via the tram - it\'s a unique fine dining experience at 2,300 feet with incredible views you can\'t get anywhere else.',
    ],
  },
];

export const SURF_SPOTS = ALL_SPOTS.filter(s => s.type === 'surf');
export const SKI_RESORTS = ALL_SPOTS.filter(s => s.type === 'ski');